"""
app.py — E-commerce Funnel & Cohort Analytics Dashboard
--------------------------------------------------------
Run with: streamlit run dashboard/app.py

Reads the processed tables from data/processed/ (generated by etl/etl_pipeline.py)
and renders an executive-style dashboard: funnel breakdown, cohort retention
heatmap, channel ROI, and monthly KPI trends — with a PM-style "what I'd do
next" recommendation panel.
"""

import os
import pandas as pd
import numpy as np
import streamlit as st
import plotly.graph_objects as go
import plotly.express as px

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROC_DIR = os.path.join(BASE, "data", "processed")

st.set_page_config(page_title="Funnel & Cohort Analytics", layout="wide", page_icon="📊")


@st.cache_data
def load_data():
    funnel_category = pd.read_csv(os.path.join(PROC_DIR, "funnel_by_category.csv"))
    funnel_device = pd.read_csv(os.path.join(PROC_DIR, "funnel_by_device.csv"))
    cohort_retention = pd.read_csv(os.path.join(PROC_DIR, "cohort_retention.csv"), index_col=0)
    monthly_kpis = pd.read_csv(os.path.join(PROC_DIR, "monthly_kpis.csv"))
    channel_cac = pd.read_csv(os.path.join(PROC_DIR, "channel_cac.csv"))
    return funnel_category, funnel_device, cohort_retention, monthly_kpis, channel_cac


try:
    funnel_category, funnel_device, cohort_retention, monthly_kpis, channel_cac = load_data()
except FileNotFoundError:
    st.error("Processed data not found. Run `python data/generate_data.py` then "
             "`python etl/etl_pipeline.py` before launching the dashboard.")
    st.stop()

st.title("📊 E-commerce Funnel & Cohort Analytics")
st.caption("Synthetic fashion e-commerce dataset (2025) · Built to demonstrate data-driven "
           "product decision-making for a PM role")

# ---------------- KPI header ----------------
latest = monthly_kpis.iloc[-1]
prev = monthly_kpis.iloc[-2] if len(monthly_kpis) > 1 else latest
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Revenue (latest mo.)", f"₹{latest['revenue_inr']/1e5:.1f}L",
          f"{(latest['revenue_inr']-prev['revenue_inr'])/prev['revenue_inr']*100:+.1f}%")
c2.metric("Orders", f"{int(latest['orders'])}",
          f"{int(latest['orders']-prev['orders']):+d}")
c3.metric("AOV", f"₹{latest['aov_inr']:.0f}")
c4.metric("Return Rate", f"{latest['return_rate_%']:.1f}%")
c5.metric("Repeat Purchase Rate", f"{latest['repeat_purchase_rate_%']:.1f}%")

st.divider()

# ---------------- Funnel ----------------
st.subheader("🔻 Conversion Funnel by Category")
fcol1, fcol2 = st.columns([2, 1])
with fcol1:
    fig = go.Figure()
    stages = ["view", "add_to_cart", "checkout", "purchase"]
    for _, row in funnel_category.iterrows():
        fig.add_trace(go.Funnel(
            name=row["category"],
            y=stages,
            x=[row[s] for s in stages],
            textinfo="value+percent initial"
        ))
    fig.update_layout(height=450, margin=dict(t=10, b=10))
    st.plotly_chart(fig, use_container_width=True)
with fcol2:
    st.markdown("**Stage-wise conversion (%)**")
    display_cols = ["category", "view_to_cart_%", "cart_to_checkout_%",
                     "checkout_to_purchase_%", "overall_view_to_purchase_%"]
    st.dataframe(funnel_category[display_cols].sort_values(
        "overall_view_to_purchase_%", ascending=False), hide_index=True, use_container_width=True)
    worst = funnel_category.sort_values("cart_to_checkout_%").iloc[0]
    st.warning(f"**Biggest leak:** {worst['category']} loses the most users between "
               f"cart → checkout ({worst['cart_to_checkout_%']:.1f}% conversion). "
               f"This stage typically flags friction in shipping cost transparency, "
               f"size/fit confidence, or payment options.")

st.divider()

# ---------------- Cohort Retention ----------------
st.subheader("📈 Monthly Cohort Retention")
st.caption("Row = signup month, Column = months since signup, Value = % of cohort making a purchase that month")
fig2 = px.imshow(
    cohort_retention.values,
    labels=dict(x="Months Since Signup", y="Signup Cohort", color="Retention %"),
    x=[str(c) for c in cohort_retention.columns],
    y=cohort_retention.index,
    color_continuous_scale="Blues",
    text_auto=".1f",
    aspect="auto"
)
fig2.update_layout(height=500)
st.plotly_chart(fig2, use_container_width=True)

m1_retention = cohort_retention["1"].mean() if "1" in cohort_retention.columns else np.nan
st.info(f"**Read:** Average Month-1 retention across cohorts is "
        f"{m1_retention:.1f}% (if computed). Retention that stabilizes rather than "
        f"trending to zero by month 3-4 suggests a genuine repeat-usage habit is forming.")

st.divider()

# ---------------- Channel CAC/ROI ----------------
st.subheader("💰 Acquisition Channel Efficiency")
ccol1, ccol2 = st.columns([1, 1])
with ccol1:
    fig3 = px.bar(channel_cac.sort_values("roi_x", ascending=True),
                  x="roi_x", y="acquisition_channel", orientation="h",
                  color="roi_x", color_continuous_scale="RdYlGn",
                  labels={"roi_x": "Revenue per user / CAC (x)", "acquisition_channel": ""})
    fig3.update_layout(height=350, margin=dict(t=10, b=10))
    st.plotly_chart(fig3, use_container_width=True)
with ccol2:
    st.dataframe(channel_cac[["acquisition_channel", "cac_inr", "revenue_per_user_inr", "roi_x"]]
                 .sort_values("roi_x", ascending=False), hide_index=True, use_container_width=True)
    best = channel_cac.sort_values("roi_x", ascending=False).iloc[0]
    worst_ch = channel_cac.sort_values("roi_x", ascending=True).iloc[0]
    st.success(f"**{best['acquisition_channel']}** returns ₹{best['roi_x']:.2f} in revenue for "
               f"every ₹1 of CAC spent — the most efficient channel.")
    st.error(f"**{worst_ch['acquisition_channel']}** returns only ₹{worst_ch['roi_x']:.2f} per ₹1 spent — "
             f"a candidate for budget reallocation.")

st.divider()

# ---------------- Monthly Trend ----------------
st.subheader("📅 Monthly KPI Trends")
kpi_choice = st.selectbox("Metric", ["revenue_inr", "orders", "aov_inr", "return_rate_%", "repeat_purchase_rate_%", "cac_inr"])
fig4 = px.line(monthly_kpis, x="month", y=kpi_choice, markers=True)
fig4.update_layout(height=350)
st.plotly_chart(fig4, use_container_width=True)

st.divider()

# ---------------- PM Recommendation Panel ----------------
st.subheader("🎯 What I'd Prioritize Next Sprint (PM Framing)")
st.markdown(f"""
1. **Fix the cart→checkout leak in {worst['category']}** — likely a fit/shipping-cost trust
   issue. Hypothesis: adding size-recommendation nudges or a "free returns" badge at checkout
   could lift conversion. Ship as an A/B test, guardrail metric = return rate (shouldn't rise).
2. **Reallocate spend away from {worst_ch['acquisition_channel']}** (lowest ROI) toward
   **{best['acquisition_channel']}** — even a 15% shift could raise blended ROI without
   increasing total budget.
3. **Investigate retention cliff after month 1** — if repeat purchase rate lags AOV growth,
   the product has an acquisition problem, not a monetization problem; prioritize lifecycle
   engagement (push/email) over paid acquisition.
""")
